from .queries import (
    INSERT_INTO_DAILY_FUTURES,
    CREATE_DAILY_FUTURES_TABLE,
    CREATE_1_MIN_FUTURES_TABLE,
    CREATE_5_MIN_FUTURES_TABLE,
    CREATE_BACKTEST_RUNS_TABLE,
    INSERT_BACKTEST_RUN,
    SELECT_ALL_BACKTEST_RUNS,
)
